### ISSUE TITLE
mXparser - v.4.0.0

### ISSUE THREAD

**Issue by mariuszgromada** [be3short/HybridSimEngine#1]
Hi :-)

Thanks for using mXparser :-) I am happy to inform that i just released v.4.0.0 - this is much better lib than before.

https://github.com/mariuszgromada/MathParser.org-mXparser/releases/tag/v.4.0.0

Best regards

BTW: Please let me know your opinion on the lib :-)

**Comment by be3short** [comment]
Hi there, sorry about the late response, thanks for the update! I think the library is great, I am hoping to eventually use it to generate code for use with the dynamical systems environment I am developing.  Keep up the good work!

**Comment by mariuszgromada** [comment]
Thx - currently there is v.4.1 version available (major update).

https://github.com/mariuszgromada/MathParser.org-mXparser/releases/tag/v.4.1.0
